In [1]:
import numpy as np

In [2]:
np.array([1,2])

array([1, 2])

In [3]:
np.array([(1,2,3), (4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.zeros((1,2))

array([[0., 0.]])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
n = 5

### Generates a matrix of 0's

In [8]:
np.zeros((n,n))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Generate a matrix of 1's

In [10]:
np.ones((n,n))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Generate a Random Array

In [12]:
np.random.random((n,n))

array([[0.85077685, 0.30485976, 0.92803927, 0.04776768, 0.14179107],
       [0.98584563, 0.69594482, 0.15125767, 0.32800113, 0.46001922],
       [0.20473046, 0.84011172, 0.04944514, 0.98825056, 0.2674759 ],
       [0.83002528, 0.56162612, 0.5368231 , 0.16668578, 0.66121059],
       [0.18735229, 0.37393554, 0.42231044, 0.06234849, 0.21200533]])

### Generates an empty array

In [13]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Properties of Arrays

In [14]:
array1 = np.zeros((4,4))

In [15]:
array1.shape

(4, 4)

In [16]:
len(array1)

4

In [18]:
array1.ndim

2

In [20]:
type(array1)
# It is interesting that in python the reserved word is type() but in javascript it is typeof()

numpy.ndarray

In [27]:
array2 = np.ones((2,4))
array2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
# Concatenate arrays
np.vstack((array1, array2))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Let's compare the difference between a numpy array and the native list in python

In [35]:
list_1 = list(range(10))
list_1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
array_1 = np.arange(0,10,1)
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
# The array is an object & the list is a native data type
# Operating on objects is computationally faster than on native data types. Let's check it out


In [45]:
for i in list_1:
    i += 5
    print(i)
list_1
# This approach does not work. Let us try another one

5
6
7
8
9
10
11
12
13
14


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
list_1 = [i + 5 for i in list_1]
list_1
# It worked ! :)

[15, 16, 17, 18, 19, 20, 21, 22, 23, 24]

In [50]:
array_1 = array_1 + 5 
array_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [56]:
# Let's check the time it takes to perform the operations, as I understand it, numpy arrays are 
# faster since they are vectorized
# Import perf.counter to measure time
from time import perf_counter
#Create the list and the numpy array
list_2 = list(range(100000))
array_2 =np.arange(0, 10000, 1)

# Time it takes a list to do it
start_time = perf_counter()
list_2 = [i + 10 for i in list_2]
end_time = perf_counter()
print("Time it took for a list: ", end_time - start_time)

# Time it takes an array to do it
start_time = perf_counter()
array_2 = array_2 + 10
end_time = perf_counter()
print("Time it took for an array: ", end_time - start_time)
print("The  numpy array is clearly more efficient, but why exactly 🤔")

Time it took for a list:  0.042172939000010956
Time it took for an array:  9.401399984199088e-05
